base/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('management/', admin.site.urls),
    path('', include('speedrun_db.urls'))
]

speedrun_db/urls.py
from django.urls import path

from . import views

app_name='speedrun_db'
urlpatterns = [
    path('', views.index, name='index'),
    path('games/', views.get_games, name='games'),
    path('run/<str:run_id>/', views.get_run, name='run'),
    path('run/<str:run_id>/splits/', views.get_splits, name='splits'),
    path('compare/<str:run_id>/', views.make_comparison, name='comparison_make'),
    path('compare/<str:run1_id>/<str:run2_id>/', views.comparison, name='comparison'),
    path('<str:game_abv>/', views.get_game, name='game'),
    path('<str:game_abv>/<str:category_abv>/', views.get_category, name='category'),
    path('<str:game_abv>/<str:category_abv>/barriers', views.category_minute_barriers, name='barriers'),
    path('<str:game_abv>/<str:category_abv>/pb', views.get_pb, name='get_pb')
]

speedrun_db/models.py
from django.contrib.auth.models import User
from django.db import models

class Game(models.Model):
    order_by = models.IntegerField()
    name = models.TextField()
    abbreviation = models.TextField()
    use_game_time = models.BooleanField()
    show_on_home = models.BooleanField()

    def __str__(self) -> str:
        return self.name

class Category(models.Model):
    order_by = models.IntegerField()
    held_game = models.ForeignKey(Game, on_delete=models.CASCADE)
    name = models.TextField()
    abbreviation = models.TextField()
    show_on_home = models.BooleanField()
    subcategory_filter = models.BooleanField()
    is_multiplayer = models.BooleanField()

    class Meta:
        verbose_name_plural = 'categories'

    def __str__(self) -> str:
        return self.name

class Run(models.Model):
    url_id = models.TextField()
    game = models.ForeignKey(Game, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    time = models.TimeField()
    date = models.DateField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    players = models.TextField(blank=True)
    video = models.TextField(blank=True)
    subcategory = models.TextField(blank=True)
    platform = models.TextField()
    demos = models.TextField(blank=True)
    splits = models.TextField(blank=True)
    offset = models.IntegerField(default=0)

    def __str__(self) -> str:
        return self.url_id

speedrun_db/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.core.exceptions import PermissionDenied
from django.http import HttpResponse, Http404

from .models import Run, Game, Category

from .func import get_games_index, convert_run, is_pb, generate_comparison, get_personal_best, compare_run

def index(request):
    run_output = get_games_index(get_pb=True)
    return render(request, 'index.html', {'runs': run_output})


def get_games(request):
    games = get_games_index(display_checks=False)
    return render(request, 'games.html', {'games': games})


def get_run(request, run_id):
    run = get_object_or_404(Run, url_id=run_id)

    context = {'run': convert_run(run), 'is_pb': is_pb(run)}
    return render(request, 'run.html', context)


def get_splits(request, run_id):
    run = get_object_or_404(Run, url_id=run_id)

    if run.splits is None:
        raise PermissionDenied
    
    splits = generate_comparison(run)
    response = HttpResponse(splits, headers={
        'Content-Type': 'application/octet-stream',
        'Content-Disposition': f'attachment; filename={run.url_id}.lss'
    })
    return response


def get_game(request, game_abv):
    game = get_object_or_404(Game, abbreviation=game_abv.lower())

    obj = {
        'abv': game.abbreviation,
        'name': game.name,
        'categories': []
    }

    for category in Category.objects.filter(held_game=game).order_by('order_by'):
        best_times = get_personal_best(category)
        times = []
        for run in best_times:
            if run is not None:
                times.append(convert_run(run))
        
        obj['categories'].append({
            'order_by': category.order_by,
            'name': category.name,
            'abv':  category.abbreviation,
            'personal_best': times
        })

    return render(request, 'game.html', {'game': obj})


def get_category(request, game_abv, category_abv):
    game = get_object_or_404(Game, abbreviation=game_abv.lower())
    category = get_object_or_404(Category, held_game=game, abbreviation=category_abv.lower())

    best_times = get_personal_best(category)
    times = []
    for run in best_times:
        if run is not None:
            times.append(convert_run(run))
    
    obj = {
        'game': {
            'name': game.name,
            'abv': game.abbreviation
        },
        'category': {
            'name': category.name,
            'abv':  category.abbreviation,
            'filter': category.subcategory_filter
        },
        'personal_best': times
    }

    runs = Run.objects.filter(category=category).order_by('-date', 'time')

    list_of_pbs = []
    for x in obj['personal_best']:
        list_of_pbs.append(x['url_id'])
    if category.subcategory_filter:
        temp = {}
        for x in runs:
            if x.url_id not in list_of_pbs:
                if x.subcategory in temp:
                    temp[x.subcategory].append(convert_run(x))
                else:
                    temp.update({str(x.subcategory): []})
                    temp[x.subcategory].append(convert_run(x))
        
        obj['run_history'] = temp
    else:
        temp = []
        for x in runs:
            if x.url_id not in list_of_pbs:
                temp.append(convert_run(x))
        obj['run_history'] = temp

    return render(request, 'category.html', {'data': obj})


def category_minute_barriers(request, game_abv, category_abv):
    game = get_object_or_404(Game, abbreviation=game_abv.lower())
    category = get_object_or_404(Category, held_game=game, abbreviation=category_abv.lower())

    obj = {
        'game': {
            'name': game.name,
            'abv': game.abbreviation
        },
        'category': {
            'name': category.name,
            'abv':  category.abbreviation,
            'filter': category.subcategory_filter
        }
    }

    runs = Run.objects.filter(category=category).order_by('date', '-time')
    run_list = []
    if category.subcategory_filter:
        temp = {}
        for x in runs:
            if x.subcategory in temp:
                if x.time.minute not in temp[x.subcategory]['queried_barriers']:
                    run_list.append(x)
                    temp[x.subcategory]['queried_barriers'].append(x.time.minute)
            else:
                temp.update({str(x.subcategory): {}})
                temp[x.subcategory]['queried_barriers'] = [x.time.minute]
                run_list.append(x)
    else:
        queried_barriers = []
        for x in runs:
            if x.time.minute not in queried_barriers:
                run_list.append(x)
                queried_barriers.append(x.time.minute)
    
    run_list.reverse()
    if category.subcategory_filter:
        temp = {}
        for x in run_list:
            if x.subcategory in temp:
                temp[x.subcategory].append(convert_run(x))
            else:
                temp.update({str(x.subcategory): []})
                temp[x.subcategory].append(convert_run(x))
        
        obj['run_history'] = temp
    else:
        temp = []
        for x in run_list:
            temp.append(convert_run(x))
        obj['run_history'] = temp

    return render(request, 'barriers.html', {'data': obj})


def get_pb(request, game_abv, category_abv):
    game = get_object_or_404(Game, abbreviation=game_abv.lower())
    category = get_object_or_404(Category, held_game=game, abbreviation=category_abv.lower())

    best_times = get_personal_best(category)
    if len(best_times) == 0 or best_times[0] is None:
        raise Http404
    else:
        return redirect('speedrun_db:run', run_id=best_times[0].url_id)


def make_comparison(request, run_id):
    run = get_object_or_404(Run, url_id=run_id)
    run_obj = convert_run(run)

    if run_obj['splits'] is None:
        raise Http404
    
    runs = Run.objects.filter(category=run.category).order_by('-date', 'time')
    if run.category.subcategory_filter:
        temp = {}
        for x in runs:
            if x.url_id != run.url_id and x.splits:
                if x.subcategory in temp:
                    temp[x.subcategory].append(convert_run(x))
                else:
                    temp.update({str(x.subcategory): []})
                    temp[x.subcategory].append(convert_run(x))
        
        run_history = temp
    else:
        temp = []
        for x in runs:
            if x.url_id != run.url_id and x.splits:
                temp.append(convert_run(x))
        run_history = temp
    
    context = {'game': run.game, 'category': run.category, 'run': convert_run(run), 'run_history': run_history, 'category_filter': run.category.subcategory_filter}
    return render(request, 'make_comparison.html', context)


def comparison(request, run1_id, run2_id):
    run1 = get_object_or_404(Run, url_id=run1_id)
    run2 = get_object_or_404(Run, url_id=run2_id)

    comparison = compare_run(run1, run2)
    if not comparison:
        # TODO: Replace with proper HTTP error
        raise Http404

    runs = [convert_run(run1), convert_run(run2)]
    load_yt_js = False
    for run in runs:
        if run['yt_player_embed']['exists']:
            load_yt_js = True
            break
    
    context = {
        'runs': [convert_run(run1), convert_run(run2)],
        'splits_comparison': comparison,
        'load_yt_js': load_yt_js
    }

    return render(request, 'compare_run.html', context)

speedrun_db/templates/barriers.html
{% extends 'base.html' %}

{% block content %}
<div class="navigator">
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'speedrun_db:index' %}">Home</a></li>
            <li class="breadcrumb-item"><a href="{% url 'speedrun_db:game' data.game.abv %}">{{ data.game.name }}</a></li>
            <li class="breadcrumb-item"><a href="{% url 'speedrun_db:category' data.game.abv data.category.abv %}">{{ data.category.name }}</a></li>
            <li class="breadcrumb-item active">Barriers</li>
        </ol>
    </nav>
</div>

<div class="run-list">
    <h1>Minute Barriers</h1>
    {% if data.category.filter %}
    {% for subcategory, runs in data.run_history.items %}
    <h4 class="subheader">{{ subcategory }}</h4>
    <div class="list-group">
        {% for run in runs %}
        <a href="{% url 'speedrun_db:run' run.url_id %}" class="list-group-item list-group-item-action">
            <div class="d-flex w-100 justify-content-between">
                <h5 class="mb-1">{{ run.timestring }}</h5>
                <small>{{ run.date }}</small>
            </div>
            {% if run.players %}
            <p class="mb-1">Completed with: {{ run.players }}</p>
            {% endif %}
        </a>
        {% endfor %}
    </div>
    {% endfor %}
    {% else %}
    <div class="list-group">
        {% for run in data.run_history %}
        <a href="{% url 'speedrun_db:run' run.url_id %}" class="list-group-item list-group-item-action">
            <div class="d-flex w-100 justify-content-between">
                <h5 class="mb-1">{{ run.timestring }}</h5>
                <small>{{ run.date }}</small>
            </div>
            {% if run.players %}
            <p class="mb-1">Completed with: {{ run.players }}</p>
            {% endif %}
        </a>
        {% endfor %}
    </div>
    {% endif %}
</div>
{% endblock content %}

speedrun_db/templates/base.html
{% load django_bootstrap5 %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title>Speedruns</title>
        
        {% bootstrap_css %}
        {% bootstrap_javascript %}
        <link rel="stylesheet" href="{% static 'style.css' %}">
    </head>
    <body>
        {% block content %}{% endblock content %}
    </body>
</html>

speedrun_db/templates/category.html
{% extends 'base.html' %}

{% block content %}
<div class="navigator">
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'speedrun_db:index' %}">Home</a></li>
            <li class="breadcrumb-item"><a href="{% url 'speedrun_db:game' data.game.abv %}">{{ data.game.name }}</a></li>
            <li class="breadcrumb-item active">{{ data.category.name }}</li>
        </ol>
    </nav>
</div>

<div class="run-list">
    <h1>Personal Best</h1>
    <div class="list-group">
        {% for run in data.personal_best %}
        <a href="{% url 'speedrun_db:run' run.url_id %}" class="list-group-item list-group-item-action">
            <div class="d-flex w-100 justify-content-between">
                <h5 class="mb-1">{{ run.timestring }}</h5>
                <small>{{ run.date }}</small>
            </div>
            {% if run.subcategory %}
            <p class="mb-1">Subcategory: {{ run.subcategory }}</p>
            {% endif %}
            {% if run.players %}
            <p class="mb-1">Completed with: {{ run.players }}</p>
            {% endif %}
        </a>
        {% endfor %}
    </div>
</div>
<br>
<div class="run-list">
    <h1>Run History</h1>
    {% if data.category.filter %}
    {% for subcategory, runs in data.run_history.items %}
    <h4 class="subheader">{{ subcategory }}</h4>
    <div class="list-group">
        {% for run in runs %}
        <a href="{% url 'speedrun_db:run' run.url_id %}" class="list-group-item list-group-item-action">
            <div class="d-flex w-100 justify-content-between">
                <h5 class="mb-1">{{ run.timestring }}</h5>
                <small>{{ run.date }}</small>
            </div>
            {% if run.players %}
            <p class="mb-1">Completed with: {{ run.players }}</p>
            {% endif %}
        </a>
        {% endfor %}
    </div>
    {% endfor %}
    {% else %}
    <div class="list-group">
        {% for run in data.run_history %}
        <a href="{% url 'speedrun_db:run' run.url_id %}" class="list-group-item list-group-item-action">
            <div class="d-flex w-100 justify-content-between">
                <h5 class="mb-1">{{ run.timestring }}</h5>
                <small>{{ run.date }}</small>
            </div>
            {% if run.players %}
            <p class="mb-1">Completed with: {{ run.players }}</p>
            {% endif %}
        </a>
        {% endfor %}
    </div>
    {% endif %}
</div>
{% endblock content %}

speedrun_db/templates/compare_run.html
{% extends 'base.html' %}

{% block content %}
<div class="navigator">
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'speedrun_db:index' %}">Home</a></li>
            <li class="breadcrumb-item"><a href="{% url 'speedrun_db:game' runs.0.game_abv %}">{{ runs.0.game_name }}</a></li>
            <li class="breadcrumb-item"><a href="{% url 'speedrun_db:category' runs.0.game_abv runs.0.category_abv %}">{{ runs.0.category_name }}</a></li>
            <li class="breadcrumb-item"><a href="{% url 'speedrun_db:run' runs.0.url_id %}">{{ runs.0.timestring }} {% if runs.0.subcategory %}({{ runs.0.subcategory }}){% endif %}</a></li>
            <li class="breadcrumb-item"><a href="{% url 'speedrun_db:comparison_make' runs.0.url_id %}">Compare</a></li>
            <li class="breadcrumb-item"><a href="{% url 'speedrun_db:run' runs.1.url_id %}">{{ runs.1.timestring }} {% if runs.1.subcategory %}({{ runs.1.subcategory }}){% endif %}</a></li>
        </ol>
    </nav>
</div>

<div class="card-group">
    {% for run in runs %}
    <div class="card run-card mx-auto">
        {% for video in run.video %}
        {% if video.type == "youtube" and run.splits and not run.use_game_time %}
        <div class="container-video">
            <div class="card-img-top video" id="{{ run.url_id }}"></div>
        </div>
        {% else %}
        <div class="container-video">
            <iframe class="card-img-top video" src="{{ video.url }}" height="562px" title="Video Player" frameborder="0" allowfullscreen></iframe>
        </div>
        {% endif %}
        {% endfor %}
        <div class="card-body">
            <h5 class="card-title mb-1">{{ run.game_name }} - {{ run.category_name }} in {{ run.timestring }} {% if run.subcategory %}({{ run.subcategory }}){% endif %}</h5>
        </div>
        <ul class="list-group list-group-flush">
            <li class="list-group-item">Achieved on {{ run.date }}</li>
            {% if run.players %}
            <li class="list-group-item">Completed with: {{ run.players }}</li>
            {% endif %}
            {% if run.platform %}
            <li class="list-group-item">Platform: {{ run.platform }}</li>
            {% endif %}
            {% if run.demos %}
            <li class="list-group-item"><a href="{{ run.demos }}" class="card-link">Demos</a></li>
            {% endif %}
        </ul>
        {% if run.splits %}
        <table class="table">
            <thead>
                <th scope="col">Split</th>
                <th>Segment Time</th>
                <th>Time</th>
            </thead>
            <tbody>
                {% if forloop.first %}
                {% for split in splits_comparison %}
                <tr>
                    {% if run.yt_player_embed.exists and not run.use_game_time %}
                    <th scope="row"><a href="#{{ run.url_id }}" onclick="seekTo({{ run.url_id }}, {{ split.split_info_1.last_seconds }} + {{ run.yt_player_embed.offset }});">{{ split.split_info_1.name }}</a></th>
                    {% else %}
                    <th>{{ split.split_info_1.name }}</th>
                    {% endif %}
                    {% if split.is_gold %}
                    <th style="color: gold;">{{ split.split_info_1.segment_time }}</th>
                    {% else %}
                    <th>{{ split.split_info_1.segment_time }}</th>
                    {% endif %}
                    <th>{{ split.split_info_1.time }}</th>
                </tr>
                {% endfor %}
                {% else %}
                {% for split in splits_comparison %}
                <tr>
                    {% if run.yt_player_embed.exists and not run.use_game_time %}
                    <th scope="row"><a href="#{{ run.url_id }}" onclick="seekTo({{ run.url_id }}, {{ split.split_info_2.last_seconds }} + {{ run.yt_player_embed.offset }});">{{ split.split_info_2.name }}</a></th>
                    {% else %}
                    <th>{{ split.split_info_2.name }}</th>
                    {% endif %}
                    {% if split.is_gold %}
                    <th>{{ split.split_info_2.segment_time }}</th>
                    {% else %}
                    <th style="color: gold;">{{ split.split_info_2.segment_time }}</th>
                    {% endif %}
                    <th>{{ split.split_info_2.time }}</th>
                </tr>
                {% endfor %}
                {% endif %}
            </tbody>
        </table>
        <div class="card-body split-links">
            <a href="{% url 'speedrun_db:splits' run.url_id %}" class="card-link">Download</a>
            <a href="{% url 'speedrun_db:comparison_make' run.url_id %}" class="card-link">Create Comparison</a>
        </div>      
        {% endif %}
    </div>
    {% endfor %}
</div>
{% if load_yt_js %}
<script>
    var tag = document.createElement('script');

    tag.src = 'https://www.youtube.com/iframe_api'
    var firstScriptTag = document.getElementsByTagName('script')[0];
    firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);

    {% for run in runs %}
    {% if run.yt_player_embed.exists and run.splits and not run.use_game_time %}
    var {{ run.url_id }};
    {% endif %}
    {% endfor %}
    function onYouTubeIframeAPIReady() {
        {% for run in runs %}
        {% if run.yt_player_embed.exists and run.splits and not run.use_game_time %}
        {{ run.url_id }} = new YT.Player('{{ run.url_id }}', {
            height: '562',
            videoId: '{{ run.yt_player_embed.video.id }}',
            playerVars: {
                'playsinline': 1,
                'start': 0
            },
        });
        {% endif %}
        {% endfor %}
    }

    function seekTo(player, seconds) {
        if (seconds < 0) seconds = 0;
        player.seekTo(seconds);
        player.playVideo();
    }
</script>
{% endif %}
{% endblock content %}

speedrun_db/templates/game.html
{% extends 'base.html' %}

{% block content %}
<div class="navigator">
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'speedrun_db:index' %}">Home</a></li>
            <li class="breadcrumb-item active" aria-current="page">{{ game.name }}</li>
        </ol>
    </nav>
</div>

<div class="category-list run-list">
    <div class="list-group">
        {% for category in game.categories %}
        <div class="list-group-item">
            <h3><a href="{% url 'speedrun_db:category' game.abv category.abv %}">{{ category.name }}</a></h3>
            {% for run in category.personal_best %}
            <a href="{% url 'speedrun_db:run' run.url_id %}">
                <div class="d-flex w-100 justify-content-between">
                    <h5 class="mb-1">{{ run.timestring }}</h5>
                    <small>{{ run.date }}</small>
                </div>
                {% if run.players %}
                <p class="mb-1">Completed with: {{ run.players }}</p>
                {% endif %}
            </a>
            {% endfor %}
        </div>
        {% endfor %}
    </div>
</div>
{% endblock content %}

speedrun_db/templates/games.html
{% extends 'base.html' %}

{% block content %}
<div class="navigator">
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'speedrun_db:index' %}">Home</a></li>
            <li class="breadcrumb-item active" aria-current="page">Games</li>
        </ol>
    </nav>
</div>

{% for game in games %}
<div class="card home-card run-list category-list">
    <h3 class="card-title"><a href="{% url 'speedrun_db:game' game.abv %}">{{ game.name }}</a></h3>
    <div class="list-group list-group-flush">
        {% for category in game.categories %}
        <div class="list-group-item">
            <h3><a href="{% url 'speedrun_db:category' game.abv category.abv %}">{{ category.name }}</a></h3>
        </div>
        {% endfor %}
    </div>
</div>
{% endfor %}
{% endblock content %}

speedrun_db/templates/index.html
{% extends 'base.html' %}

{% block content %}
<div class="navigator">
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item active" aria-current="page">Home</li>
        </ol>
    </nav>
</div>

{% for game in runs %}
<div class="card home-card run-list category-list">
    <h3 class="card-title"><a href="{% url 'speedrun_db:game' game.abv %}">{{ game.name }}</a></h3>
    <div class="list-group list-group-flush">
        {% for category in game.categories %}
        <div class="list-group-item">
            <h3><a href="{% url 'speedrun_db:category' game.abv category.abv %}">{{ category.name }}</a></h3>
            {% for run in category.personal_best %}
            <a href="{% url 'speedrun_db:run' run.url_id %}">
                <div class="d-flex w-100 justify-content-between">
                    <h5 class="mb-1">{{ run.timestring }}</h5>
                    <small>{{ run.date }}</small>
                </div>
                {% if run.players %}
                <p class="mb-1">Completed with: {{ run.players }}</p>
                {% endif %}
            </a>
            {% endfor %}
        </div>
        {% endfor %}
    </div>
</div>
{% endfor %}
{% endblock content %}

speedrun_db/templates/make_comparison.html
{% extends 'base.html' %}

{% block content %}
<div class="navigator">
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'speedrun_db:index' %}">Home</a></li>
            <li class="breadcrumb-item"><a href="{% url 'speedrun_db:game' run.game_abv %}">{{ run.game_name }}</a></li>
            <li class="breadcrumb-item"><a href="{% url 'speedrun_db:category' run.game_abv run.category_abv %}">{{ run.category_name }}</a></li>
            <li class="breadcrumb-item"><a href="{% url 'speedrun_db:run' run.url_id %}">{{ run.timestring }} {% if run.subcategory %}({{ run.subcategory }}){% endif %}</a></li>
            <li class="breadcrumb-item active">Compare</li>
        </ol>
    </nav>
</div>

<div class="run-list">
    <h1>Valid Comparisons</h1>
    {% if category_filter %}
    {% for subcategory, runs in run_history.items %}
    <h4 class="subheader">{{ subcategory }}</h4>
    <div class="list-group">
        {% for hist_run in runs %}
        <a href="{% url 'speedrun_db:comparison' run.url_id hist_run.url_id %}" class="list-group-item list-group-item-action">
            <div class="d-flex w-100 justify-content-between">
                <h5 class="mb-1">{{ hist_run.timestring }}</h5>
                <small>{{ hist_run.date }}</small>
            </div>
            {% if hist_run.players %}
            <p class="mb-1">Completed with: {{ hist_run.players }}</p>
            {% endif %}
        </a>
        {% endfor %}
    </div>
    {% endfor %}
    {% else %}
    <div class="list-group">
        {% for hist_run in run_history %}
        <a href="{% url 'speedrun_db:comparison' run.url_id hist_run.url_id %}" class="list-group-item list-group-item-action">
            <div class="d-flex w-100 justify-content-between">
                <h5 class="mb-1">{{ hist_run.timestring }}</h5>
                <small>{{ hist_run.date }}</small>
            </div>
            {% if hist_run.players %}
            <p class="mb-1">Completed with: {{ hist_run.players }}</p>
            {% endif %}
        </a>
        {% endfor %}
    </div>
    {% endif %}
</div>
{% endblock content %}

speedrun_db/templates/run.html
{% extends 'base.html' %}

{% block content %}
<div class="navigator">
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'speedrun_db:index' %}">Home</a></li>
            <li class="breadcrumb-item"><a href="{% url 'speedrun_db:game' run.game_abv %}">{{ run.game_name }}</a></li>
            <li class="breadcrumb-item"><a href="{% url 'speedrun_db:category' run.game_abv run.category_abv %}">{{ run.category_name }}</a></li>
            <li class="breadcrumb-item active" aria-current="page">{{ run.timestring }} {% if run.subcategory %}({{ run.subcategory }}){% endif %}</li>
        </ol>
    </nav>
</div>

<div class="card run-card mx-auto">
    {% for video in run.video %}
    {% if video.type == "youtube" and run.splits and not run.use_game_time %}
    <div class="container-video">
        <div class="card-img-top video" id="{{ run.url_id }}"></div>
    </div>
    {% else %}
    <div class="container-video">
        <iframe class="card-img-top video" src="{{ video.url }}" height="562px" title="Video Player" frameborder="0" allowfullscreen></iframe>
    </div>
    {% endif %}
    {% endfor %}
    <div class="card-body">
        <h5 class="card-title mb-1">{{ run.game_name }} - {{ run.category_name }} in {{ run.timestring }} {% if run.subcategory %}({{ run.subcategory }}){% endif %}</h5>
    </div>
    <ul class="list-group list-group-flush">
        <li class="list-group-item">Achieved on {{ run.date }}</li>
        {% if run.players %}
        <li class="list-group-item">Completed with: {{ run.players }}</li>
        {% endif %}
        {% if run.platform %}
        <li class="list-group-item">Platform: {{ run.platform }}</li>
        {% endif %}
        {% if run.demos %}
        <li class="list-group-item"><a href="{{ run.demos }}" class="card-link">Demos</a></li>
        {% endif %}
    </ul>
    {% if run.splits %}
    <table class="table">
        <thead>
            <th scope="col">Split</th>
            <th>Segment Time</th>
            <th>Time</th>
        </thead>
        <tbody>
            {% for split in run.splits %}
            <tr>
                {% if run.yt_player_embed.exists and not run.use_game_time %}
                <th scope="row"><a href="#{{ run.url_id }}" onclick="seekTo({{ run.url_id }}, {{ split.last_seconds }} + {{ run.yt_player_embed.offset }});">{{ split.name }}</a></th>
                {% else %}
                <th>{{ split.name }}</th>
                {% endif %}
                <th>{{ split.segment_time }}</th>
                <th>{{ split.time }}</th>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <div class="card-body split-links">
        <a href="{% url 'speedrun_db:splits' run.url_id %}" class="card-link">Download</a>
        <a href="{% url 'speedrun_db:comparison_make' run.url_id %}" class="card-link">Create Comparison</a>
    </div>      
    {% endif %}
</div>
{% if run.yt_player_embed.exists and run.splits and not run.use_game_time %}
<script>
    var tag = document.createElement('script');

    tag.src = 'https://www.youtube.com/iframe_api'
    var firstScriptTag = document.getElementsByTagName('script')[0];
    firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);

    var {{ run.url_id }};
    function onYouTubeIframeAPIReady() {
        {{ run.url_id }} = new YT.Player('{{ run.url_id }}', {
            height: '562',
            videoId: '{{ run.yt_player_embed.video.id }}',
            playerVars: {
                'playsinline': 1,
                'start': 0
            },
        });
    }

    function seekTo(player, seconds) {
        if (seconds < 0) seconds = 0;
        player.seekTo(seconds);
        player.playVideo();
    }

</script>
{% endif %}

{% endblock content %}